apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: hello-innovative-eventlistener 
spec:
  serviceAccountName: pipeline
  triggers:
  - name: hello-innovative-trigger
    interceptors:
    - cel:
        filter: >-
          body.commits[0].title.split(" ")[0] == "hello-innovative"
        overlays:
        - key: working-dir
          expression: 'body.commits[0].title.split(" ")[0]'
    bindings:
    - kind: ClusterTriggerBinding       
      ref: hello-innovative-binding
    template:
      ref: hello-innovative-template
