apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-innovative-test
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: hello-innovative-pipeline
  params:
  - name: deployment-name
    value: "hello-innovative"
  - name: git-url
    value: "https://github.com/sforeman-rh/hello-innovative-tekton.git"
  - name: git-revision
    value: "master"
  - name: IMAGE
    value: "image-registry.openshift-image-registry.svc:5000/hello-innovative/hello-innovative:latest"
  - name: TLSVERIFY
    value: "false"
  - name: working-dir
    value: "hello-innovative"
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: tekton-pvc
