---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"pipeline","namespace":"tailwinds"},"secret":{"name":"git-ssh"}}
secret:
  name: git-ssh
